2024-12-31 23:35:16,622 [INFO] Локальный сервер запущен на 127.0.0.1:8888
2024-12-31 23:35:25,761 [INFO] Подключение от ('127.0.0.1', 61387)
2024-12-31 23:35:25,780 [INFO] Получено от клиента: GET / HTTP/1.1
Host: 127.0.0.1:8888
Accept: */*
Accept-Encoding: gzip, deflate
User-Agent: Python/3.13 aiohttp/3.11.11


2024-12-31 23:35:25,788 [ERROR] Ошибка при пересылке на прокси-сервер: [WinError 64] Указанное сетевое имя более недоступно
2024-12-31 23:40:48,072 [INFO] Локальный сервер запущен на 127.0.0.1:8888
2024-12-31 23:40:56,887 [INFO] Подключение от ('127.0.0.1', 49701)
2024-12-31 23:40:56,907 [INFO] Получено от клиента: GET / HTTP/1.1
Host: 127.0.0.1:8888
Accept: */*
Accept-Encoding: gzip, deflate
User-Agent: Python/3.13 aiohttp/3.11.11


2024-12-31 23:40:56,914 [ERROR] Ошибка при пересылке на прокси-сервер: Server disconnected
2024-12-31 23:45:57,647 [INFO] Клиент ('127.0.0.1', 49701) отключился.
2025-01-01 00:46:32,077 [INFO] Локальный сервер запущен на 127.0.0.1:8888
2025-01-01 00:48:25,616 [INFO] Подключение от ('127.0.0.1', 54534)
2025-01-01 00:48:25,616 [INFO] Получено от клиента: GET / HTTP/1.1
Host: 127.0.0.1:8888
Accept: */*
Accept-Encoding: gzip, deflate
User-Agent: Python/3.13 aiohttp/3.11.11


2025-01-01 00:48:25,623 [ERROR] Ошибка при пересылке на прокси-сервер: Server disconnected
2025-01-01 00:53:21,441 [INFO] Локальный сервер запущен на 127.0.0.1:8888
2025-01-01 00:53:29,637 [INFO] Подключение от ('127.0.0.1', 54646)
2025-01-01 00:53:29,637 [INFO] Получено от клиента: GET / HTTP/1.1
Host: 127.0.0.1:8888
Accept: */*
Accept-Encoding: gzip, deflate
User-Agent: Python/3.13 aiohttp/3.11.11


2025-01-01 00:53:29,642 [ERROR] Ошибка при пересылке на прокси-сервер: Server disconnected
2025-01-01 00:58:30,626 [INFO] Клиент ('127.0.0.1', 54646) отключился.
2025-01-01 01:02:17,738 [INFO] Локальный сервер запущен на 127.0.0.1:8888
2025-01-01 01:02:26,652 [INFO] Подключение от ('127.0.0.1', 54778)
2025-01-01 01:02:26,678 [ERROR] Ошибка: 'utf-8' codec can't decode byte 0xfc in position 8: invalid start byte
2025-01-01 01:02:26,679 [INFO] Клиент ('127.0.0.1', 54778) отключился.
2025-01-01 01:12:35,677 [INFO] Локальный сервер запущен на https://127.0.0.1:8888
2025-01-01 01:12:49,312 [INFO] Подключение от ('127.0.0.1', 54966)
2025-01-01 01:12:49,313 [INFO] Получено от клиента: b'GET / HTTP/1.1\r\nHost: 127.0.0.1:8888\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: Python/3.13 aiohttp/3.11.11\r\n\r\n'
2025-01-01 01:12:49,320 [ERROR] Ошибка при пересылке на прокси-сервер: Server disconnected
2025-01-01 01:17:49,631 [INFO] Клиент ('127.0.0.1', 54966) отключился.
2025-01-01 01:23:08,758 [INFO] Локальный сервер запущен на https://127.0.0.1:8888
2025-01-01 01:23:21,993 [INFO] Подключение от ('127.0.0.1', 55192)
2025-01-01 01:23:21,994 [INFO] Получено от клиента: b'GET / HTTP/1.1\r\nHost: 127.0.0.1:8888\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: Python/3.13 aiohttp/3.11.11\r\n\r\n'
2025-01-01 01:23:22,008 [ERROR] Ошибка при пересылке на прокси-сервер: Server disconnected
2025-01-06 06:38:00,238 [INFO] Локальный сервер запущен на https://127.0.0.1:8888
2025-01-06 06:38:20,152 [INFO] Подключение от ('127.0.0.1', 55380)
2025-01-06 06:38:20,153 [INFO] Получено от клиента: b'GET / HTTP/1.1\r\nHost: 127.0.0.1:8888\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: Python/3.13 aiohttp/3.11.11\r\n\r\n'
2025-01-06 06:38:22,190 [ERROR] Ошибка при пересылке на прокси-сервер: Cannot connect to host 127.0.0.1:8080 ssl:default [Удаленный компьютер отклонил это сетевое подключение]
2025-01-06 06:41:25,523 [INFO] Локальный сервер запущен на https://127.0.0.1:8888
2025-01-06 06:41:40,768 [INFO] Подключение от ('127.0.0.1', 55493)
2025-01-06 06:41:40,769 [INFO] Получено от клиента: b'GET / HTTP/1.1\r\nHost: 127.0.0.1:8888\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: Python/3.13 aiohttp/3.11.11\r\n\r\n'
2025-01-06 06:41:42,793 [ERROR] Ошибка при пересылке на прокси-сервер: Cannot connect to host 127.0.0.1:8080 ssl:default [Удаленный компьютер отклонил это сетевое подключение]
2025-01-06 06:57:45,347 [INFO] Локальный сервер запущен на https://127.0.0.1:8888
2025-01-06 06:57:57,477 [INFO] Подключение от ('127.0.0.1', 55605)
2025-01-06 06:57:57,478 [INFO] Получено от клиента: b'GET / HTTP/1.1\r\nHost: 127.0.0.1:8888\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: Python/3.13 aiohttp/3.11.11\r\n\r\n'
2025-01-06 06:57:59,510 [ERROR] Ошибка при пересылке на прокси-сервер: Cannot connect to host 127.0.0.1:8080 ssl:default [Удаленный компьютер отклонил это сетевое подключение]
2025-01-06 06:59:05,821 [INFO] Локальный сервер запущен на https://127.0.0.1:8888
2025-01-06 07:08:09,723 [INFO] Локальный сервер запущен на https://127.0.0.1:8888
2025-01-06 07:08:11,951 [INFO] Подключение от ('127.0.0.1', 55755)
2025-01-06 07:08:11,952 [INFO] Получено от клиента: b'GET / HTTP/1.1\r\nHost: 127.0.0.1:8888\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: Python/3.13 aiohttp/3.11.11\r\n\r\n'
2025-01-06 07:08:13,977 [ERROR] Ошибка при пересылке на прокси-сервер: Cannot connect to host 127.0.0.1:8080 ssl:default [Удаленный компьютер отклонил это сетевое подключение]
2025-01-06 07:56:29,951 [INFO] Локальный сервер запущен на https://127.0.0.1:8888
2025-01-06 07:56:38,651 [INFO] Подключение от ('127.0.0.1', 59449)
2025-01-06 07:56:38,652 [INFO] Получено от клиента: b'GET / HTTP/1.1\r\nHost: 127.0.0.1:8888\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: Python/3.13 aiohttp/3.11.11\r\n\r\n'
2025-01-06 07:56:40,685 [ERROR] Ошибка при пересылке на прокси-сервер: Cannot connect to host 127.0.0.1:8080 ssl:default [Удаленный компьютер отклонил это сетевое подключение]
